### ISSUE TITLE
update to rand 0.7

### ISSUE THREAD

**Issue by reyk** [rpgp/rpgp#80]
Hi,

rpgp uses rand 0.6 while we're currently at rand 0.7. The APIs are not compatible but rpgp needs an "old"-style rng for encryption. I could prepare a diff but unfortunately some of rpgp's dependencies are also stuck on the old rand crate so it isn't that easy.

My current hack...workaround with the release version of rpgp is to include both rand crates in my project:

```toml
rand = "0.7"
old_rand = { version = "0.6", package = "rand" }
```

..to use it for `encrypt_to_keys`:

```rust
let mut rng = old_rand::thread_rng();
```

Reyk
